### ISSUE TITLE
FAHClient version

### ISSUE THREAD

**Issue by wandhydrant** [yurinnick/folding-at-home-docker#10]
Hello!

Currently you have ``version="v7.5"`` in your Dockerfile. Right now they published 7.6.9. Is there a reason for staying on 7.5 ?

**Comment by yurinnick** [comment]
No really, I just didn't know about the update. I will update the image in the following days.

Speaking of which, would you like to merge our efforts and support both CPU and GPU image in the same repo, but having different tags for it? I can provide you a maintainer status if you'd like.

**Comment by wandhydrant** [comment]
With pleasure! It's just that I don't want to publish anything on the Docker hub. If you or somebody else takes care of that, or sets up any kind of automatic pipeline, no problem.

**Comment by wandhydrant** [comment]
I can start by preparing a first PR today or tomorrow.

**Comment by PattaFeuFeu** [comment]
Now addressed by #11 and #12

**Comment by yurinnick** [comment]
Completed by #11
