### ISSUE TITLE
How to run behind proxy?

### ISSUE THREAD

**Issue by pinki** [yurinnick/folding-at-home-docker#14]
How can I run this image behind a proxy?

**Comment by yurinnick** [comment]
Sorry, I don't have the answer for this. Please direct you question to any Docker community, I think they can help you to figure out the setup.

**Comment by wandhydrant** [comment]
Have a look at FAHClient options. From the output of ``/opt/fahclient/FAHClient --help`` :
```
Network:
  proxy <string=>
    Set proxy for outgoing HTTP connections

  proxy-enable <boolean=false>
    Enable proxy configuration

  proxy-pass <string=>
    Set password for proxy connections

  proxy-user <string=>
    Set user name for proxy connections
```
You can pass any FAHClient option at the end of the "docker run" line.
