### ISSUE TITLE
Lost points after container restart

### ISSUE THREAD

**Issue by 501st-alpha1** [yurinnick/folding-at-home-docker#16]
A few times now I've had my F@H lose some of my points after restarting the Docker container; do you have any idea why that would happen?  It's not all of my points; last time it went from ~2.5M to ~2.1M.  I would expect any progress on current jobs to be lost, but my understanding is the points are for past jobs already submitted to the server.

I'm using @wandhydrant's GPU-enabled [image](https://github.com/wandhydrant/folding-at-home-docker-gpu) (from before it was merged back into this repo), in case that makes a difference.  I also pass the username and team number to the container at startup, and then enter my passcode manually in the UI.  It doesn't seem like that should make a difference, but I think I'll try giving the passcode at startup too, just in case.

Interestingly, [my F@H stats page](https://stats.foldingathome.org/donor/501st_alpha1) still shows the higher number, so maybe my client isn't pulling that properly for some reason?

Any idea why this is happening?  Does this even sound like a problem with the Docker image, or should I talk to F@H directly?

**Comment by yurinnick** [comment]
My best guess is that container loses some temporary data upon restart, so you lose your progress till the last checkpoint. You need to use persistent storage mount for safe restarts, simply mount FAH data directory as a [volume](https://docs.docker.com/storage/volumes/) to a hosts directory, so FAH will recover after restart.

**Comment by wandhydrant** [comment]
I agree with you - in the worst case your current work should be lost, nothing that has been submitted to the server!

Just to be sure, we are only talking about container *restarts* here, no re-creation of the container? In the latter case, all data is lost unless the work directory was mounted as a volume.

I'm not very happy with the restart behaviour either. F@h is supposed to checkpoint every N minutes, N is by default 15. Once I stopped a container a few minutes after it started a new work unit. When I started it again, I expected it to start the work unit from zero - but instead it declared the work unit as corrupted (I don't remember the exact wording). I think "docker stop" may be too brutal, or not wait long enough for a proper stop. It might be better to stop F@h through its web interface, or through FAHControl.

**Comment by yurinnick** [comment]
I don't know how exactly FAH handles tmp data, but `docker stop` cleans up tmpfs, so if anything was there, it's gone. I think it's worth it to add documentation on how to setup persistent storage mount.

**Comment by 501st-alpha1** [comment]
Thanks, that's a good suggestion, I was wondering about that.

According to [the docs](https://foldingathome.org/faqs/installation-guides/linux/file-locations/):

> The cores, logs, and work folder, plus current log file, are located here:
>
> `/var/lib/fahclient`

I don't see that folder in my container, but I do see `cores`, `work`, and a log file in the `/opt/fahclient` folder.  I'll try mounting those two folders and will report back.

---

What's really confusing to me is why I lose *some* of my points.  It would make sense if I lost all of them (if they are only tracked locally), or none of them (if it fetches from the server whenever it starts), but I can't figure out why I would only lose some.  (And I've been folding today, and my points have gone up both locally and on the server, but neither one was reset to match the other.)

**Comment by yurinnick** [comment]
That reminds me that #8 was merged for exactly this reason. And you need to mount the whole FAH dir, `/opt/fahclient/work` should be enough.

**Comment by yurinnick** [comment]
Added persistent storage documentation and example

**Comment by 501st-alpha1** [comment]
I've now updated my script to mount `work` as suggested, and have started the container for the first time since, so I'll report back if I have any issues.

Interestingly, my points now show up correctly, even though the `work` directory was empty, since this was my first time mounting it.  I did click `Stop Folding` in the UI prior to stopping the container, which I'm not sure I did prior times.

**Comment by 501st-alpha1** [comment]
Now I'm really confused.  I haven't restarted the container since my last comment, and have been folding off and on, but now my local points are ~400k short of my F@H stats page (but still higher than they were before). :thinking:

**Comment by 501st-alpha1** [comment]
After starting up again, my points were reset to the value on my F@H stats page.  Also now that `work` has been mounted across runs, I've been able to keep partial WU progress, nice. :raised_hands:

**Comment by yurinnick** [comment]
Thanks for doing your research! This looks a bit weird for me, but I still think that there's some logic around checkpoints that you get all or nothing until you reach some threashhold. You may want to ask FAH develepers on the forum/github about it.

**Comment by 501st-alpha1** [comment]
Yeah I'm still a little confused haha.  It's been 3 more days of folding off and on, and my points are still correct, so at this point I'll probably just write it off.  (But if I do run into this issue again, I'll report back here and/or report it to FAH.)

Thanks for all the help!
