### ISSUE TITLE
Failed to open database 'work/client.db'

### ISSUE THREAD

**Issue by chimanos** [yurinnick/folding-at-home-docker#20]
Hello, I have an issue when I try to start the docker container with the client.db I have the following error:

`ERROR:Exception: Failed to open database 'work/client.db': unable to open database file`

Command for launch:

`docker run -d --name folding-at-home -p 7396:7396 -p 36330:36330 -e USER=Test -e TEAM=0 -e ENABLE_GPU=false -e ENABLE_SMP=true -e POWER=full -v /home/test/fah:/opt/fahclient/work --restart unless-stopped yurinnick/folding-at-home:latest --allow 0/0 --web-allow 0/0
`

Do you have any idea ? Thanks

**Comment by yurinnick** [comment]
I apologize for taking so long to respond to this issue. It's linked to [docker/compose#3270], basically Docker always mount volumes as root and there is no way around it. There are a few things can be down: 1. Use root user inside the container, which may compromise security 2. Implement [s6init](https://www.skarnet.org/software/s6-linux-init/) to fix permissions before starting FAH. 3. Don't use mounts, but you'll lose all uncompleted data between restartes.

I would explore option 2, meanwhile I'd recomment to start container as root user by adding `--user root` parameter and fixing permissions for the directory by running `chown -R folding:folding /opt/fahclient/work`
