### ISSUE TITLE
Nvidia support (fork)

### ISSUE THREAD

**Issue by wandhydrant** [yurinnick/folding-at-home-docker#3]
Hello! Thanks for your Dockerfile. I mixed it with the BOINC Nvidia Dockerfile to create one with Nvidia GPU access: https://github.com/wandhydrant/folding-at-home-docker-gpu

I had to change the base image to Nvidia's Ubuntu image. Do you want me to make a PR here?

**Comment by yurinnick** [comment]
Since it's interchangeable functionality it's better to keep these two in a separate images. However we can keep the codebase in one repository, or we can create links in the documentation.

**Comment by wandhydrant** [comment]
OK! I've put in links from the start.

**Comment by ssbarnea** [comment]
I think it would a much better approach to join efforts and provide a single image.  Maintenance effort would be lower and using it will also be easier.

It is clearly not a pleasure to start containers on a bunch of hosts, which may have different hardware, some w/o GPU, some w/. Ideally the container should be able to use, whatever it finds.
