### ISSUE TITLE
Container image is missing CUDA and OpenCL libraries

### ISSUE THREAD

**Issue by ssbarnea** [yurinnick/folding-at-home-docker#4]
Apparently these containers are missing the libcuda and libopencl:

![](https://sbarnea.com/ss/Screen-Shot-2020-03-11-18-40-01.png)

**Comment by ghost** [comment]
Instead of `debian:stable-slim` as the base image, you can use `nvidia/cuda:10.0` which includes cuda
(https://github.com/NVIDIA/nvidia-docker)

I think the run command will also need the `--gpus all` argument
https://github.com/NVIDIA/nvidia-docker#usage

**Comment by yurinnick** [comment]
There is a fork with OpenCL/Cuda support: https://github.com/wandhydrant/folding-at-home-docker-gpu.

Initially, I wasn't intended to support an image with GPU support, but with a growing number of requests, it might be a good idea.

**Comment by keivanB** [comment]
Hi guys, 
I am trying to run this docker image in an NSF funded data center to help folding home.  I will do my best to update it with a required CUDA libraries, however, I really appreciate it if you guys can also work on this to make it deploy-able asap. You can reach me at bahmank@clarkson.edu

**Comment by ghost** [comment]
@keivanB Use the fork that @yurinnick mentioned. It works perfectly.

**Comment by 501st-alpha1** [comment]
@yurinnick The fork mentioned works for me, so this isn't urgent, but I'd be in favor of adding GPU support to your image FWIW.  If you don't want to bloat the main image for those who don't need it, maybe you could have a version with GPU support as a separate Docker tag.

**Comment by yurinnick** [comment]
Sorry folks, I am having a lot of activities on my primary job for now. I'd like to work with @wandhydrant on merging code bases and keep a single repository with multiple tags for cpu/gpu images.

**Comment by wandhydrant** [comment]
Now that the code bases have been merged, I guess this can be closed :-)
