### ISSUE TITLE
CPU limits

### ISSUE THREAD

**Issue by BlinkyStitt** [yurinnick/folding-at-home-docker#5]
How do you recommend setting CPU limits? I'm not running docker swarm, so I'm using docker-compose version 2 configs instead of version 3.

Theres a lot of options listed at https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources, and I'm not sure what is optimal to use. I'm thinking cpus, cpu_shares, and cpuset should be enough.

There's also a slider in the web UI. Is that maybe available as a flag?

**Comment by BlinkyStitt** [comment]
Actually, it looks like FAHClient has options for a lot of limits. I'm going to use these.

```
folding@d79efa54cde2:/opt/fahclient$ /opt/fahclient/FAHClient --help
Usage: /opt/fahclient/FAHClient [[--config] <filename>] [OPTIONS]...

Configuration options:
The following options can be specified in a configuration file or on the command
line using the following syntax:

    --<option> <value>

  or:

    --<option>=<value>

  or when marking boolean values true:

    --<option>

Client Control:
  client-threads <integer=6>
    The number of client processing threads.

  cycle-rate <double=4>
    The maximum cycle frequency in Hz of client threads.

  cycles <integer=-1>
    Run at most this many cycles. A value less than zero means run indefinitely.

  idle-seconds <integer=300>
    Number of seconds of system idle time before enabling idle folding. Set to
    zero to ignore system idle time.

  core-priority <string=idle>
    Set the core priority. Valid values are: idle or low

  cpu-affinity <boolean=false>
    If true, try to lock core processes to a fixed CPU

  cpu-usage <integer=100>
    The maximum percentage of the CPU a core should use. Not implemented by all
    cores.

  gpu-usage <integer=100>
    GPU usage as a percent from 10-100

  cpus <integer=-1>
    How many CPUs a slot should use. <= 0 will use all the CPUs detected in the
    system.

  idle <boolean=false>
    Only run slot when idle.

  power <string=medium>
    Set the client's power level. Valid values are 'light', 'medium' or 'full'.
    This setting affects the defaults of several other options such as 'cpus',
    'pause-on-battery', etc.

```

**Comment by yurinnick** [comment]
It's up to you which method to choose, it's possible to configure CPU usage both on docker side and in fahclient. Personally I prefer to use dockers resource control, `cpu` is very simple, specify number of cores (float values allowed) and you're good to go.

In case you don't want to use dockers resource control, feel free to use fahclient capabilities. Without specifying resource limits, docker just shares all resources with the container by default.

**Comment by yurinnick** [comment]
Feel free to reopen if you still have other questions.
