### ISSUE TITLE
Configuring multiple CPU slots

### ISSUE THREAD

**Issue by IvantheDugtrio** [yurinnick/folding-at-home-docker#6]
I'm having issues passing the options for configuring multiple CPU slots, as it seems most GROMACS work units crash when allocated more than 16 cores. Is there a way to pass all of the config information from a config file?

**Comment by yurinnick** [comment]
It's it possible to use all standard FAHClient flags, including `--config <string=config.xml>` for providing XML configuration.

The full command should be something similar to:
```
docker run \
  --name folding-at-home \
  -p 7396:7396 \
  -p 36330:36330 \
  -e USER=Anonymous \
  -e TEAM=0 \
  -e ENABLE_GPU=false \
  -e ENABLE_SMP=true \
  -v $(pwd)/config.xml:/opt/fahclient/config.xml \
  --restart unless-stopped \
  yurinnick/folding-at-home
  --config /opt/fahclient/config.xml
```

Unfortunately I don't have hardware for testing. Please report back whether it's working for you or not.
