### ISSUE TITLE
Update URL on this repo for docker hub

### ISSUE THREAD

**Issue by irstevenson** [yurinnick/folding-at-home-docker#7]
Thanks for providing this image. Just a heads up that the link you've set for the repo is the one which requires you to authenticate first to docker hub. I'd suggest instead you use the publicly accessible one of: https://hub.docker.com/r/yurinnick/folding-at-home

It'll make it more accessible to people. ;)

**Comment by yurinnick** [comment]
Updated. Thanks for reporting!
